name: "Build Preview Deployment"

on:
    pull_request:
        types: [opened, synchronize]

jobs:
    build-preview:
        runs-on: "ubuntu-latest"
        name: "Build Preview Site and Upload Build Artifact"
        steps:
            - name: "checkout"
              uses: "actions/checkout@v6"
              with:
                  fetch-depth: 0
                  ref: ${{ github.event.pull_request.head.ref }}
                  repository: ${{ github.event.pull_request.head.repo.full_name }}
            - uses: pnpm/action-setup@v6
            - uses: actions/setup-node@v6
              with:
                  node-version: "24"
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm --filter=web run build
            - name: "upload build artifact"
              uses: "actions/upload-artifact@v7"
              with:
                  name: "preview-build"
                  path: |
                    node_modules
                    web/.svelte-kit
                    web/node_modules
                  include-hidden-files: true
