name: Deploy to Cloudflare Pages

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: bun install
      - name: Build frontend
        run: cd web && bun run build
      - name: "Deploy to Cloudflare Pages"
        uses: "AdrianGonz97/refined-cf-pages-action@v1"
        with:
            apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
            accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
            githubToken: ${{ secrets.GITHUB_TOKEN }}
            projectName: "diffs"
            directory: "web/.svelte-kit/cloudflare"
            deploymentName: Production
        env:
            GITHUB_CLIENT_SECRET: ${{ secrets.VITE_GITHUB_CLIENT_SECRET }}
